### PR TITLE
Single streamer

### PR DESCRIPTION
**Pull request by alcantara09**

### CODE REVIEW

**Comment by planthaber** [comment]
Thanks for your contribution.

I don't really get what your Task does different compared to the Streamer configured with only one port.

Wouldn't it be better to use orogens subclassing and create the port by calling

createInput(::video_streamer_vlc::PortConfig const & config) with the values for the specific port in configure?

**Comment by doudou** [comment]
> I don't really get what your Task does different compared to the Streamer configured with only one port.

The point of the change is that the current streamer task has a design that goes contrary to a good design in Rock:
1. each port is basically separate from another, so why bundle the functionality in a single task, instead of having the framework spawn as many tasks as it needs ? (bad observability on the component's behavior and CPU/memory usage)
2. because of (1), it's using operations to configure itself (usage complexity)
3. (1) has the effect that the task's code is a lot more complex that it could be (all the port management) (code complexity)

**Comment by planthaber** [comment]
As far as I remember, there were issues with libvlc using static pointers internally.

https://vlc-devel.videolan.narkive.com/9lOrBdsv/problems-with-many-libvlc-instances

The post is 13 Years old, but they still use the static pointer:
https://github.com/videolan/vlc/blob/master/src/libvlc.h#L203

So, the SingleStreamer task will fail as soon someone puts two of them in the same deployment, while working fine when deployed in the default deployment.

I guess this will be very hard to debug once it happens.

**Comment by doudou** [comment]
> The post is 13 Years old, but they still use the static pointer:

The link you posted is not referring to a global static pointer. It's resolving the private data pointer from a pointer passed from the caller. The method is static, the instance is not global.

**Comment by planthaber** [comment]
Additionally, the configurable thread already uses multiple instances of the VLCStreamer class ;-)

I guess we should remove the old Streamer task and rename this one from SingleStreamer to Streamer.

**Comment by doudou** [comment]
> I guess we should remove the old Streamer task and rename this one from SingleStreamer to Streamer.

Well, if someone depends on the current task, he'll get his system broken so :-1: 

Let's gracefully deprecate the current task and have `SingleStreamer` as it is.

**Pull request merged**
